name: Build and Release

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: gradle

    - name: Build Magisk Module
      run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        ./gradlew :module:assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: module-zip
        path: out/*.zip # <-- ИСПРАВЛЕННЫЙ ПУТЬ

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download module artifact
        uses: actions/download-artifact@v4
        with:
          name: module-zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.event.inputs.package_name }}-${{ github.run_id }}
          name: Module for ${{ github.event.inputs.package_name }}
          body: |
            Automated build for package: `${{ github.event.inputs.package_name }}`
            Triggered by: @${{ github.actor }}
          files: ./*.zip
